version: '3'
services:
  backend:
    container_name: server
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo
    build:
      context: .
      dockerfile: DockerFile
  mongo:
    container_name: mongo_container
    image: mongo
    ports:
     - '27017:27017'
  frontend:
    container_name: app
    build:
        context: ./my-app/
        dockerfile: ./DockerFile
    image: react
    ports:
        - "3000:3000"   
